# Generated by Django 4.2 on 2024-05-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='Estudiante_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante'),
        ),
    ]
